### PR TITLE
Add sym/cmp for SPS30

### PR DESCRIPTION
**Pull request by dbrgn**
##### SUMMARY

Add a sym / cmp for SPS30 particulate matter sensor.

Since the sensor has a 5-pin connector, I did not add any device (since it may be connected differently depending on the project).

sps30

##### CHECKLIST

- [x] I have read and followed the [library conventions](https://docs.librepcb.org/#libraryconventions).
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the [CC0 Public Domain License](https://en.wikipedia.org/wiki/CC0), allowing everyone to use and modify the content without any restrictions.

### CODE REVIEW

**Comment by ubruhin** [comment]
Hmm, since this sensor cannot be mounted directly on a PCB, what do we need this symbol for? :see_no_evil: I suspect you actually want to place a *connector* on the PCB, don't you? :wink:

**Comment by dbrgn** [comment]
Actually, at this stage I don't know yet how I will connect the sensor. I'm still designing the circuits/schematics.

During the design phase I prefer to add symbols that represent the type of device they stand for. If we have custom symbols for temperature and humidity sensors, why should I place a generic connector symbol next to those two just because this specific particle sensor comes in a package that uses wired connections instead of soldered connections?

This is just the symbol and component, so a user would need to create a custom device depending on how the final product is being assembled. (Or for schematic-only applications, the component can be used as-is.) I agree that devices which map components to generic connectors should not be added to the standard library.

If you think that it should be a general policy that solderless devices should not have their own symbols/components in the standard library, then we should clearly state that in the library convention docs.

**Comment by dbrgn** [comment]
The SPS30 has a JST ZH series connector. Many projects will probably use the same connector on the opposite end, so that a ZH-ZH double-ended cable can be used.

@ubruhin would you accept a device in this library that maps the SPS30 to the [JST S5B-ZR](https://github.com/LibrePCB-Libraries/JST.lplib/pull/2) header?

**Comment by ubruhin** [comment]
> @ubruhin would you accept a device in this library that maps the SPS30 to the JST S5B-ZR header?

With the package in the JST library (added as dependency here), right?

I really don't like it, but I agree it would be handy for users... I *might* accept such a device ;)

**Review by ubruhin — APPROVED** [review]
Looks good so far, I'd agree to merge it without waiting for a concrete device :+1:

**Comment by dbrgn** [comment]
> With the package in the JST library (added as dependency here), right?

Yes!

Thanks for the review.

**Pull request merged**
